name: Check mainnet configuration

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:

    - name: Install Nix
      uses: cachix/install-nix-action@v14

    - name: Setup nix cache
      run: |
        sudo mkdir -p /etc/nix
        cat <<EOF | sudo tee /etc/nix/nix.conf
        substituters = https://cache.nixos.org https://hydra.iohk.io
        trusted-public-keys = iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=

    - uses: actions/checkout@v2

    - name: Refresh cardano-node mainnet configuration
      run: |
        SOURCE=$(nix-build $(pwd)/release.nix -A cardano-deployment)
        TARGET=$(pwd)/configuration/cardano

        copyFile() {
          echo $1
          cp ${SOURCE}/$1 ${TARGET}/$1
        }

        copyFile "mainnet-alonzo-genesis.json"
        copyFile "mainnet-byron-genesis.json"
        copyFile "mainnet-config.json"
        copyFile "mainnet-shelley-genesis.json"
        copyFile "mainnet-topology.json"

    - name: Check mainnet for mainnet configuration differences
      run: |
        git diff --exit-code
